### ISSUE TITLE
GC heap size vs committed

### ISSUE THREAD

**Issue by ladeak** [Maoni0/mem-doc#9]
In the last sentence of the following paragraph, I get into some confusion:
https://github.com/Maoni0/mem-doc/blob/master/doc/.NETMemoryPerformanceAnalysis.md#special-handling-of-the-ephemeral-segment

>  it means this difference can be large, e.g., if there are 32 heaps and each heap has a 50 MB gen0 budget and you look at the heap size right after a GC, the size you see is going to be (32 * 50 = 1.6 GB) less than the committed bytes.

a few lines above it says the gen0 budget will be committed, but my understanding is that the "heap size" term would include "free objects" or in other words all committed memory. So shouldn't the heap size always refer to more than the committed?

**Comment by Maoni0** [comment]
interesting, I didn't get any notification for this so only saw it just now. sorry about that!

free objects are made out of free spaces inbetween live objects. we don't make a free object after the last live object - that free space is called "end of segment" space and we just record that for that segment. so the heap size you get would not include that space because gen0 would end at the last object in gen0.

please let me know if this does not make sense.

**Comment by ladeak** [comment]
Ok, so it is clear this way. "heap size" does not include allocation budget. Thank you for the clarification.
